config/routes.rb
Rails.application.routes.draw do
  get 'up' => 'rails/health#show', as: :rails_health_check


  resources :lists, only: [:index, :new, :create, :show] do
    resources :bookmarks, only: [:new, :create, :destroy]
  end

  root to: 'lists#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie, :list, presence: true
  validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy
  has_one_attached :photo

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks

  validates :title, :overview, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list), notice: "Your bookmark is created!"
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.save
    redirect_to list_path(@list)
  end

  private

  def list_params
    params.require(:list).permit(:name, photos: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/_form.html.erb
<div class="col-md-6">
      <%= simple_form_for [@list, Bookmark.new] do |f| %>
      <%= f.association :movie %>
      <%= f.input :comment, input_html: { class: 'form-control' } %>
      <%= f.button :submit, 'Add movie', class: "btn btn-primary btn-lg px-4" %>
      <% end %>
      <%= link_to 'Back to List', list_path(@list), class: "btn btn-secondary btn-lg mt-3 px-4" %>
  </div>

app/views/bookmarks/create.html.erb
<h1>Bookmarks#create</h1>
<p>Find me in app/views/bookmarks/create.html.erb</p>

app/views/bookmarks/new.html.erb
<div class="container mt-5">
  <h1 class="text-center">Add a movie</h1>
  <%= render "form", bookmark: @bookmark %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="container mt-5">
  <h1>My movie lists</h1>
  <hr class="col-3">
    <div class="col-6">
      <%# <ul class="list-group"> %>
        <% @lists.each do |list| %>
          <li class="list-group-item">
              <% if list.photo != nil %>
              <div class="card" style="background-image: linear-gradient(rgba(0, 0, 0, 0.3), rgba(0,0,0,0.3)), url('<%= cl_image_tag list.photo.key, height: 300, width: 400, crop: :fill %>')">
              <% else%>
              <div class="card" style="background-image: linear-gradient(rgba(0, 0, 0, 0.3), rgba(0,0,0,0.3)), url('<%= list.url %>')">
              <% end %>
              <%= link_to list.name, list_path(list) %>
              </div>
          </li>
        <% end %>
      <%# </ul> %>
      <%= link_to "Add new list", "new", class: "btn btn-primary mt-3" %>
    </div>
</div>

app/views/lists/new.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-12 text-center mb-4">
      <h1 class="display-4">New List</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <%= simple_form_for @list do |f| %>
        <%= f.input :name, input_html: { class: 'form-control' } %>
        <%= f.input :photo, as: :file %>
        <%= f.button :submit, 'Create List', class: "btn btn-primary btn-lg" %>
      <% end %>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<div class="container mt-5">
  <h1><%= @list.name %></h1>
  <hr>
  <div class="container mt-5 d-flex">
      <% @list.bookmarks.each do |bookmark| %>
          <div class="card m-4" style="width: 16rem;">
              <img class="card-img-top" src="<%= bookmark.movie.poster_url %>" alt="<%= bookmark.movie.title %>'s poster">
                <div class="card-body">
                  <p class="card-text"><strong><%= bookmark.movie.title%></strong></p>
                  <p class="card-text"><%= bookmark.comment %></p>
                  <p class="card-text"><strong>Rating:</strong> <%= bookmark.movie.rating %></p>
                  <%= link_to 'Delete', list_bookmark_path(@list, bookmark), data: {turbo_method: :delete, turbo_confirm: "Are you sure?!"}, class: 'btn btn-danger btn-sm' %>
                </div>
          </div>
          <% end %>
  </div>
  <hr class="col-12">
  <h3>Add a movie</h3>
  <br>
  <div>
  <%= render "bookmarks/form", list: @list, bookmark: @bookmark %>
  </div>
  <br>
</div>